# Where web/build.sh --deploy publishes the site (sourced by bash).
# Owner's choice B (2026-10-03): the source repository becomes private; the site lives in its own public repository
# that holds only the built game. Until that repository exists, the site stays in the source repository.
#   1. create the public repository on GitHub (empty: no README, no licence)
#   2. change PAGES_REPO below to it, then run web/build.sh --deploy (it creates the gh-pages branch with the CNAME)
#   3. GitHub: old repository Settings > Pages: remove the custom domain; new repository Settings > Pages: deploy from
#      the gh-pages branch, custom domain injoker.relifes.net, Enforce HTTPS
#   4. old repository Settings > General > Danger zone: change visibility to private
PAGES_REPO="hawonjungo/ThreeElements"
PAGES_BRANCH="gh-pages"
